/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LandingIndexRouteImport } from './routes/_landing.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPlayersRouteImport } from './routes/dashboard/players'
import { Route as DashboardLeaderboardsRouteImport } from './routes/dashboard/leaderboards'
import { Route as DashboardGamesRouteImport } from './routes/dashboard/games'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api-keys'
import { Route as LandingSignUpRouteImport } from './routes/_landing.sign-up'
import { Route as LandingSignInRouteImport } from './routes/_landing.sign-in'
import { Route as DashboardGamesGameIdRouteImport } from './routes/dashboard/games.$gameId'
import { Route as DashboardLeaderboardLeaderboardIdIndexRouteImport } from './routes/dashboard/leaderboard/$leaderboardId.index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlayersRoute = DashboardPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaderboardsRoute = DashboardLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGamesRoute = DashboardGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const LandingSignUpRoute = LandingSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LandingRoute,
} as any)
const LandingSignInRoute = LandingSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardGamesGameIdRoute = DashboardGamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => DashboardGamesRoute,
} as any)
const DashboardLeaderboardLeaderboardIdIndexRoute =
  DashboardLeaderboardLeaderboardIdIndexRouteImport.update({
    id: '/leaderboard/$leaderboardId/',
    path: '/leaderboard/$leaderboardId/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof LandingSignInRoute
  '/sign-up': typeof LandingSignUpRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/games': typeof DashboardGamesRouteWithChildren
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/games/$gameId': typeof DashboardGamesGameIdRoute
  '/dashboard/leaderboard/$leaderboardId': typeof DashboardLeaderboardLeaderboardIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof LandingSignInRoute
  '/sign-up': typeof LandingSignUpRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/games': typeof DashboardGamesRouteWithChildren
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/': typeof LandingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/games/$gameId': typeof DashboardGamesGameIdRoute
  '/dashboard/leaderboard/$leaderboardId': typeof DashboardLeaderboardLeaderboardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_landing/sign-in': typeof LandingSignInRoute
  '/_landing/sign-up': typeof LandingSignUpRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/games': typeof DashboardGamesRouteWithChildren
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/players': typeof DashboardPlayersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/_landing/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/games/$gameId': typeof DashboardGamesGameIdRoute
  '/dashboard/leaderboard/$leaderboardId/': typeof DashboardLeaderboardLeaderboardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/api-keys'
    | '/dashboard/games'
    | '/dashboard/leaderboards'
    | '/dashboard/players'
    | '/dashboard/profile'
    | '/'
    | '/dashboard/'
    | '/dashboard/games/$gameId'
    | '/dashboard/leaderboard/$leaderboardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/api-keys'
    | '/dashboard/games'
    | '/dashboard/leaderboards'
    | '/dashboard/players'
    | '/dashboard/profile'
    | '/'
    | '/dashboard'
    | '/dashboard/games/$gameId'
    | '/dashboard/leaderboard/$leaderboardId'
  id:
    | '__root__'
    | '/_landing'
    | '/dashboard'
    | '/_landing/sign-in'
    | '/_landing/sign-up'
    | '/dashboard/api-keys'
    | '/dashboard/games'
    | '/dashboard/leaderboards'
    | '/dashboard/players'
    | '/dashboard/profile'
    | '/_landing/'
    | '/dashboard/'
    | '/dashboard/games/$gameId'
    | '/dashboard/leaderboard/$leaderboardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/players': {
      id: '/dashboard/players'
      path: '/players'
      fullPath: '/dashboard/players'
      preLoaderRoute: typeof DashboardPlayersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaderboards': {
      id: '/dashboard/leaderboards'
      path: '/leaderboards'
      fullPath: '/dashboard/leaderboards'
      preLoaderRoute: typeof DashboardLeaderboardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/games': {
      id: '/dashboard/games'
      path: '/games'
      fullPath: '/dashboard/games'
      preLoaderRoute: typeof DashboardGamesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_landing/sign-up': {
      id: '/_landing/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof LandingSignUpRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/sign-in': {
      id: '/_landing/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof LandingSignInRouteImport
      parentRoute: typeof LandingRoute
    }
    '/dashboard/games/$gameId': {
      id: '/dashboard/games/$gameId'
      path: '/$gameId'
      fullPath: '/dashboard/games/$gameId'
      preLoaderRoute: typeof DashboardGamesGameIdRouteImport
      parentRoute: typeof DashboardGamesRoute
    }
    '/dashboard/leaderboard/$leaderboardId/': {
      id: '/dashboard/leaderboard/$leaderboardId/'
      path: '/leaderboard/$leaderboardId'
      fullPath: '/dashboard/leaderboard/$leaderboardId'
      preLoaderRoute: typeof DashboardLeaderboardLeaderboardIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface LandingRouteChildren {
  LandingSignInRoute: typeof LandingSignInRoute
  LandingSignUpRoute: typeof LandingSignUpRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingSignInRoute: LandingSignInRoute,
  LandingSignUpRoute: LandingSignUpRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface DashboardGamesRouteChildren {
  DashboardGamesGameIdRoute: typeof DashboardGamesGameIdRoute
}

const DashboardGamesRouteChildren: DashboardGamesRouteChildren = {
  DashboardGamesGameIdRoute: DashboardGamesGameIdRoute,
}

const DashboardGamesRouteWithChildren = DashboardGamesRoute._addFileChildren(
  DashboardGamesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardGamesRoute: typeof DashboardGamesRouteWithChildren
  DashboardLeaderboardsRoute: typeof DashboardLeaderboardsRoute
  DashboardPlayersRoute: typeof DashboardPlayersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLeaderboardLeaderboardIdIndexRoute: typeof DashboardLeaderboardLeaderboardIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardGamesRoute: DashboardGamesRouteWithChildren,
  DashboardLeaderboardsRoute: DashboardLeaderboardsRoute,
  DashboardPlayersRoute: DashboardPlayersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLeaderboardLeaderboardIdIndexRoute:
    DashboardLeaderboardLeaderboardIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
